import { z } from 'zod';

// ============================================================================
// SECTION CHAT INPUT
// Used for the chat at the end of explanation/section units where users can
// ask questions or request extra practice. Supports tool calling for
// lesson-update-structure.
// ============================================================================

export const SectionChatInputSchema = z.object({
  /** The user's current message */
  userMessage: z.string().describe("The user's message or question."),

  /** Target language being learned */
  targetLanguage: z
    .string()
    .default('Spanish')
    .describe('The language being learned.'),

  /** User's native language */
  nativeLanguage: z
    .string()
    .default('English')
    .describe("The user's native language."),

  /** User's proficiency level */
  userLevel: z
    .string()
    .default('beginner')
    .describe('The user proficiency level.'),

  /** The explanation content the user just read (context for the current section) */
  sectionContext: z
    .string()
    .describe(
      'The content of the current section/explanation the user is on.',
    ),

  /** XML lesson plan structure up to the current point */
  lessonPlanContext: z
    .string()
    .describe(
      'The XML lesson plan structure up to and including the current unit.',
    ),

  /** Chat history (last N messages) */
  chatHistory: z
    .array(
      z.object({
        role: z.enum(['user', 'assistant']),
        content: z.string(),
      }),
    )
    .optional()
    .default([])
    .describe('Previous messages in the conversation (max 10).'),
});

export type SectionChatInput = z.infer<typeof SectionChatInputSchema>;

// ============================================================================
// SECTION CHAT RESPONSE EVENTS (SSE)
// The section chat can produce two types of events:
// 1. Regular streamed text (like explanation chat)
// 2. A "generate_extra_units" tool call result with new compiled sections
// ============================================================================

export const SectionChatToolCallSchema = z.object({
  /** The specific instruction generated by the LLM for the update-structure prompt */
  instruction: z.string(),
});

export type SectionChatToolCall = z.infer<typeof SectionChatToolCallSchema>;


